### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by liujing1** [shreyassanthu77/webview_dart#2]
可以麻烦提供运行需要的webview.dll么？运行webviewCreate的时候崩溃

**Comment by shreyassanthu77** [comment]
Uhmm i don't understand whatever language you are speaking but from Google translate i understand that you need the DLL files which are in the releases section if you have any other questions please ask them in English :)

**Comment by kira2015** [comment]
https://github.com/webview/webview/issues/404 
这里有你要的答案
